spring.application.name=festival-flow-api
spring.datasource.url = jdbc:postgresql://localhost:5432/festival_flow_db
spring.datasource.username = postgres
spring.datasource.password =${password}
spring.jpa.hibernate.ddl-auto = validate
